import SendIcon from "@mui/icons-material/Send";
import {
  Button
} from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { FORM, GITHUB, TWITTER } from "../config/constant";
import githubWhite from "../public/github-white.svg";
import github from "../public/github.svg";
import logo from "../public/logo.jpg";
import twitterWhite from "../public/twitter-white.svg";
import twitter from "../public/twitter.svg";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container} style={{ padding: 0 }}>
      <Head>
        <title>Naritoshi Karimata</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.PNG" />
      </Head>

      <main className={styles.main}>
        <div className={styles.top}>
          <div>
            <Image
              style={{ borderRadius: "999px", border: "4px solid #fff" }}
              width={160}
              src={logo}
              alt="logo"
            />
          </div>
          <div className={styles.profile}>
            <h1 className={styles.profile_name}>狩俣 成駿</h1>
            <p className={styles.profile_job}>WEBエンジニア志望</p>
            <p className={styles.profile_description}>
              沖縄県でプログラミングを学んでいる24卒の就活生 /
              思いやりをカタチにして届けられるWEBエンジニアになりたい /
              月１で映画鑑賞 / 好きな言葉は「Don&apos;t think, just do.」
            </p>
          </div>
          <div className={styles.social}>
            <Link href={TWITTER} target="_blank" rel="noopener noreferrer">
              <Image width={28} src={twitter} alt="logo" />
            </Link>
            <Link href={GITHUB} target="_blank" rel="noopener noreferrer">
              <Image width={28} src={github} alt="logo" />
            </Link>
          </div>
        </div>
        <hr
          width="100%"
          noshade=""
          size="1"
          style={{ borderColor: "#E0E7EF" }}
        />
        <Link href={FORM} target="_blank" rel="noopener noreferrer">
          <Button
            sx={{
              padding: "12px 24px",
              borderRadius: 10,
              letterSpacing: 1.5,
              border: "2px solid #1E1E1E",
              backgroundColor: "#1E1E1E",
              "&:hover": {
                backgroundColor: "#FFFFFF",
                transition: ".3s",
                color: "#1E1E1E",
              },
              position: "fixed",
              bottom: 40,
              right: 32,
            }}
            variant="contained"
            endIcon={<SendIcon />}
          >
            メッセージを送信
          </Button>
        </Link>
      </main>

      <footer className={styles.footer}>
        <div className={styles.social}>
          <Link href={TWITTER} target="_blank" rel="noopener noreferrer">
            <Image width={28} src={twitterWhite} alt="logo" />
          </Link>
          <Link href={GITHUB} target="_blank" rel="noopener noreferrer">
            <Image width={28} src={githubWhite} alt="logo" />
          </Link>
        </div>
        <p>© 2023 Naritoshi Karimata</p>
      </footer>
    </div>
  );
}
